server:
  port: 8090  # Users service port

# Disable Eureka client
eureka:
  client:
    enabled: false
  instance:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interior_booking_app
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    org.springframework: INFO
